common:
    lid_topic:  "/iv_points"
    gps_topic: "/ublox_driver/receiver_pvt"
    imu_topic:  "/mavros/imu/data_raw"
    uwb_topic: "/nlink_linktrack_nodeframe2"
    mag_topic: "/mavros/imu/mag"
    vicon_topic: "/vrpn_client_node/uwb_ngx_tag/pose"
    wmm_cof_path: "/home/mint/ws_uav_setup/src/igo_eskf/config/WMM.COF"
    file_save_path: "/home/mint/ws_uav_setup/src/igo_eskf/data/"
    en_vicon: true
    en_debug: true
    en_time_sync: true         # ONLY turn on when external time synchronization is really not possible

params:
    init_bias:
        gyro: [2.0e-6, 2.0e-6, 2.0e-6]
        accel: [3.0e-6, 3.0e-6, 3.0e-6]
        mag: [1.0e-6, 1.0e-6, 1.0e-6]
    cov: # init pior cov 
        posi: [1.0e-6, 1.0e-6, 1.0e-6]
        vel: [1.0e-6, 1.0e-6, 1.0e-6]
        ori: [1.0e-6, 1.0e-6, 1.0e-6]
        gyro_bias: [1.0e-6, 1.0e-6, 1.0e-6]
        acc_bias: [1.0e-6, 1.0e-6, 1.0e-6]
        mag_bias: [1.0e-6, 1.0e-6, 1.0e-6]
        g_bias: [1.0e-6, 1.0e-6, 1.0e-6]
    process: # process noise, 
        vel: [1.0e-6, 1.0e-6, 1.0e-6]
        rot: [1.0e-3, 1.0e-3, 1.0e-3]
        gyro: [1.0e-1, 1.0e-1, 1.0e-1]
        accel: [3.0e-1, 3.0e-1, 3.0e-1]
        mag: [1.0e-3, 1.0e-3, 1.0e-3]
    measurement: # measurement noise
        posi: [1.0e-6, 1.0e-6, 1.0e-6]
        vel: [1.0e-3, 1.0e-3, 1.0e-3]
        mag: [1.0e-3, 1.0e-3, 1.0e-3]

options:
    local_gravity: 9.79484197226504
    en_sensor_init: true
    init_duration: 5 # seconds
    imu_filter_n_sigma: 10
    imu_slide_window_size: 5
    en_rtk_vel: false
        
publish:
    path_en:  true
    pose_topic: "/fusion_pose"
    odom_topic: "/fusion_odom"
    path_topic: "/fusion_path"
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

mapping:
    extrinsic_T: [ 0.0, 0.0, 0.0 ]
    extrinsic_R: [ 1.0, 0.0, 0.0,
                                0.0, 1.0, 0.0,
                                0.0, 0.0, 1.0]